name: Run tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.6
          cache: pip
      - run: make create_venv
      - run: make test
        id: test
      - run: cat generated_workflow.yml
        if: failure() && steps.test.outcome == 'failure'

  verify:
    uses: ./.github/workflows/reference_workflow.yml
    with:
      filename: "foo.txt"
      count: 5
      dry_run: true
